<?php
/**
 * Created by PhpStorm.
 * User: vlad_
 * Date: 21.01.2018
 * Time: 16:35
 */

namespace App\Services;

use App\Repositories\BlogRepository;
use App\Repositories\CategoryRepository;

class BlogService extends LayoutService
{
    protected $blogRepository;

    public function __construct(CategoryRepository $categoryRepository, BlogRepository $blogRepository)
    {
        parent::__construct($categoryRepository);

        $this->blogRepository = $blogRepository;
    }
    
    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub
    }

    public function fillBlog($model)
    {
        $model->blog = $this->blogRepository->getBlog($model);

        if (!$model->blog)
        {
            abort(404);
        }
    }
    
    public function incrementBlogViewCount($model)
    {
        $this->blogRepository->incrementBlogViewCount($model);
    }

    public function fillPopularBlogs($model)
    {
        $model->popularBlogs = $this->blogRepository->getPopularBlogs($model);
    }
    
    public function fillAllBlogs($model)
    {
        $model->blogs = $this->blogRepository->getAllBlogs($model);

        if ($model->blogs->count() < 1)
        {
            abort(404);
        }
    }
    
    public function fillAllBlogsCount($model)
    {
        $model->blogsCount = $this->fillAllBlogsCount($model);
    }
}