<?php
/**
 * Created by PhpStorm.
 * User: vlad_
 * Date: 16.11.2017
 * Time: 11:22
 */

namespace App\Services;


use App\Repositories\CategoryRepository;
use App\Repositories\FilterRepository;
use App\Repositories\ProductRepository;

class CategoryFiltersService extends LayoutService
{
    /**
     * @var CategoryRepository
     */
    public $categoryRepository;

    /**
     * @var ProductRepository
     */
    public $productRepository;

    /**
     * @var FilterRepository
     */
    public $filterRepository;

    /**
     * CategoryService constructor.
     * @param CategoryRepository $categoryRepository
     * @param ProductRepository $productRepository
     * @param FilterRepository $filterRepository
     */
    public function __construct(CategoryRepository $categoryRepository, ProductRepository $productRepository, FilterRepository $filterRepository)
    {
        parent::__construct($categoryRepository);

        $this->categoryRepository = $categoryRepository;

        $this->productRepository = $productRepository;

        $this->filterRepository = $filterRepository;
    }

    /**
     * @param $model
     */
    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub

        $this->fillCurrentCategory($model);

        $this->fillCategoryProducts($model);

        $this->fillCountCategoryProducts($model);

        $this->fillFilters($model);
    }

    /**
     * @param $model
     */
    private function fillCurrentCategory($model)
    {
        $model->currentCategory = $this->categoryRepository->getCurrentCategoryBySlug($model->slug, $model->language);
    }

    private function fillCategoryProducts($model)
    {
        $userTypeId = $model->userTypeId;

        if ($userTypeId == 4)
        {
            $userTypeId = 1;
        }

        $model->categoryProducts = $this->productRepository->getAllProductsForFiltersCategory(
            $model->currentCategory,
            $model->categoryProductsLimit,
            $model->categoryProductsOffset,
            $model->language,
            $userTypeId,
            $model
        );
    }

    private function fillCountCategoryProducts($model)
    {
        $model->countCategoryProducts = $this->productRepository->getCountProductsFiltersCategory($model);
    }

    private function fillFilters($model)
    {

        $filtersArray = $this->filterRepository->initActiveFilters($model);

        $filters = [];

        foreach (collect($filtersArray) as $item)
        {
            $filterName = $item->filter_name_title;

            $filters[$filterName][] = $item;
        }
        \Debugbar::info($model->filters);
        
        $model->filters = collect($filters);

        \Debugbar::info($model->filters);
    }
}