<?php
/**
 * Created by PhpStorm.
 * User: vlad_
 * Date: 22.02.2018
 * Time: 12:26
 */

namespace App\Services;


use App\Repositories\CategoryRepository;

class CooperationService extends LayoutService
{
    public function __construct(CategoryRepository $categoryRepository)
    {
        parent::__construct($categoryRepository);
    }

    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub

        $this->fillMetaTags($model);
    }

    private function fillMetaTags($model)
    {
        $model->title = trans('header.cooperation');
        $model->description = trans('header.cooperation');
        $model->keywords = trans('header.cooperation');
        $model->h1 = trans('header.cooperation');
    }
}