<?php
/**
 * Created by PhpStorm.
 * User: vlad_
 * Date: 20.12.2017
 * Time: 17:31
 */

namespace App\Services;


use App\Repositories\CategoryRepository;

class ErrorService extends LayoutService
{
    public function __construct(CategoryRepository $categoryRepository)
    {
        parent::__construct($categoryRepository);
    }
    
    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub
    }
}