<?php
/**
 * Created by PhpStorm.
 * User: vlad_
 * Date: 20.12.2017
 * Time: 17:31
 */

namespace App\Services;

use App\Repositories\CategoryRepository;

/**
 * Class ErrorService
 * @package App\Services
 */
class ErrorService extends LayoutService
{
    /**
     * ErrorService constructor.
     * @param CategoryRepository $categoryRepository
     */
    public function __construct(CategoryRepository $categoryRepository)
    {
        parent::__construct($categoryRepository);
    }

    /**
     * @param $model
     */
    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub
    }
}