<?php
/**
 * Created by PhpStorm.
 * User: vlad_
 * Date: 23.01.2018
 * Time: 17:46
 */

namespace App\Services;


use App\Repositories\CategoryRepository;

class LookBookService extends LayoutService
{
    public function __construct(CategoryRepository $categoryRepository)
    {
        parent::__construct($categoryRepository);
    }
    
    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub
    }
}