<?php
/**
 * Created by PhpStorm.
 * User: vlad_
 * Date: 23.01.2018
 * Time: 17:46
 */

namespace App\Services;


use App\Repositories\CategoryRepository;
use App\Repositories\MetaTagRepository;

class LookBookService extends LayoutService
{
    protected $metaTagRepository;

    public function __construct(CategoryRepository $categoryRepository,
                                MetaTagRepository $metaTagRepository)
    {
        parent::__construct($categoryRepository);

        $this->metaTagRepository = $metaTagRepository;
    }
    
    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub

        $this->fillMetaTags($model);
    }

    private function fillMetaTags($model)
    {
        $metaTag = $this->metaTagRepository->getMetaTagByPageName($model);
        $model->title = $metaTag->title;
        $model->description = $metaTag->description;
        $model->keywords = $metaTag->keywords;
        $model->h1 = $metaTag->h1;
    }
}