<?php
/**
 * Created by PhpStorm.
 * User: vlad_
 * Date: 19.03.2018
 * Time: 12:01
 */

namespace App\Services;


use App\Repositories\CategoryRepository;

class OrderPaymentService extends LayoutService
{
    public function __construct(CategoryRepository $categoryRepository)
    {
        parent::__construct($categoryRepository);
    }

    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub
    }
}