<?php
/**
 * Created by PhpStorm.
 * User: vlad_
 * Date: 14.12.2017
 * Time: 12:47
 */

namespace App\Services;

use App\Repositories\CategoryRepository;
use App\Repositories\DeliveryRepository;
use App\Repositories\MetaTagRepository;
use App\Repositories\OrderProductRepository;
use App\Repositories\OrderRepository;
use App\Repositories\PaymentRepository;
use App\Repositories\ProductRepository;
use App\Repositories\ProfileRepository;
use App\Repositories\UserRepository;
use App\Repositories\WishListProductRepository;

/**
 * Class ProfileService
 * @package App\Services
 */
class ProfileService extends LayoutService
{
    /**
     * @var UserRepository
     */
    protected $userRepository;

    /**
     * @var ProfileRepository
     */
    protected $profileRepository;

    /**
     * @var PaymentRepository
     */
    protected $paymentRepository;

    /**
     * @var DeliveryRepository
     */
    protected $deliveryRepository;

    /**
     * @var WishListProductRepository
     */
    protected $wishListProductRepository;

    /**
     * @var ProductRepository
     */
    protected $productRepository;

    /**
     * @var OrderRepository
     */
    protected $orderRepository;

    /**
     * @var OrderProductRepository
     */
    protected $orderProductRepository;

    protected $metaTagRepository;

    public function __construct(CategoryRepository $categoryRepository, 
                                UserRepository $userRepository, 
                                ProfileRepository $profileRepository,
                                PaymentRepository $paymentRepository,
                                DeliveryRepository $deliveryRepository,
                                WishListProductRepository $wishListProductRepository,
                                ProductRepository $productRepository,
                                OrderRepository $orderRepository,
                                OrderProductRepository $orderProductRepository,
                                MetaTagRepository $metaTagRepository)
    {
        parent::__construct($categoryRepository);
        
        $this->userRepository = $userRepository;
        
        $this->profileRepository = $profileRepository;
        
        $this->paymentRepository = $paymentRepository;
        
        $this->deliveryRepository = $deliveryRepository;

        $this->wishListProductRepository = $wishListProductRepository;

        $this->productRepository = $productRepository;

        $this->orderRepository = $orderRepository;
        
        $this->orderProductRepository = $orderProductRepository;

        $this->metaTagRepository = $metaTagRepository;
    }

    /**
     * @param $model
     */
    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub

        $this->fillMetaTags($model);
    }

    /**
     * save user name
     * @param $userId
     * @param $name
     */
    public function saveUserName($userId, $name)
    {
        $this->userRepository->saveUserName($userId, $name);
    }

    /**
     * save phone number
     * @param $userId
     * @param $phone
     */
    public function saveProfilePhoneNumber($userId, $phone)
    {
        $this->profileRepository->saveProfilePhoneNumber($userId, $phone);
    }

    /**
     * check if email changed
     * @param $userId
     * @param $email
     * @return bool
     */
    public function checkIfEmailChanged($userId, $email)
    {
        return $this->userRepository->checkIfEmailChanged($userId, $email);
    }

    /**
     * check if new email valid
     * @param $email
     * @return bool
     */
    public function checkIfNewEmailValid($email)
    {
        return $this->userRepository->checkIfNewEmailValid($email);
    }

    /**
     * save new email
     * @param $userId
     * @param $email
     */
    public function saveNewEmail($userId, $email)
    {
        $this->userRepository->saveNewEmail($userId, $email);
    }

    /**
     * change password
     * @param $userId
     * @param $newPassword
     */
    public function changePassword($userId, $newPassword)
    {
        $this->userRepository->changePassword($userId, $newPassword);
    }

    /**
     * fill payments
     * @param $model
     */
    public function fillPayments($model)
    {
        $model->payments = $this->paymentRepository->getAllPayments($model);
    }

    /**
     * fill deliveries
     * @param $model
     */
    public function fillDeliveries($model)
    {
        $model->deliveries = $this->deliveryRepository->getAllDeliveries($model);
    }

    /**
     * fill selected payment id
     * @param $model
     */
    public function fillSelectedPaymentId($model)
    {
        $model->selectedPaymentId = $this->profileRepository->getSelectedPaymentId($model);
    }

    /**
     * fill selected delivery id
     * @param $model
     */
    public function fillSelectedDeliveryId($model)
    {
        $model->selectedDeliveryId = $this->profileRepository->getSelectedDeliveryId($model);
    }

    public function fillSelectedDelivery($model)
    {
        $model->delivery = $this->deliveryRepository->getDelivery($model);
    }

    /**
     * fill address
     * @param $model
     */
    public function fillAddress($model)
    {
        $model->address = $this->profileRepository->getAddress($model);
    }

    /**
     * save payment delivery
     * @param $paymentId
     * @param $deliveryId
     * @param $address
     */
    public function savePaymentDelivery($deliveryId, $address)
    {
        $this->profileRepository->savePaymentDelivery($deliveryId, $address);
    }

    /**
     * add product to wish list
     * @param $wishListId
     * @param $productId
     * @param $sizeId
     */
    public function addToWishList($wishListId, $productId, $sizeId)
    {
        $this->wishListProductRepository->addToWishList($wishListId, $productId, $sizeId);
    }

    /**
     * delete product from wish list
     * @param $wishListProductId
     */
    public function deleteFromWishList($wishListProductId)
    {
        $this->wishListProductRepository->deleteFromWishList($wishListProductId);
    }

    /**
     * return wish list items with products
     * @param $wishListId
     * @param $language
     * @param $userTypeId
     * @return array
     */
    public function getWishListItems($wishListId, $language, $userTypeId)
    {
        $wishListProducts = $this->wishListProductRepository->getWishListProducts($wishListId);

        $productIds = [];

        $wishListItems = [];

        $newWishListItems = [];
        
        foreach ($wishListProducts as $wishListProduct)
        {
            $productIds[] = $wishListProduct->product_id;
            $wishListItems[] = [
                'productId' => $wishListProduct->product_id,
                'sizeId' => $wishListProduct->size_id,
                'wishListProductId' => $wishListProduct->id
            ];
        }

        $products = $this->productRepository->getWishListProducts($productIds, $language, $userTypeId);

        foreach ($wishListItems as $wishListItem)
        {
            foreach ($products as $product)
            {
                if ($wishListItem['productId'] == $product->id)
                {
                    $newWishListItems[] = [
                        'wishListProductId' => $wishListItem['wishListProductId'],
                        'productId' => $wishListItem['productId'],
                        'sizeId' => $wishListItem['sizeId'],
                        'product' => $product
                    ];
                    $wishListItem['product'] = $product;
                }
            }
        }
        
        return $newWishListItems;
    }

    /**
     * return wish list products count
     * @param $wishListItems
     * @return int
     */
    public function getTotalWishListCount($wishListItems)
    {
        return count($wishListItems);
    }

    /**
     * get orders
     * @param $model
     */
    public function getOrders($model)
    {
        $model->orders = $this->orderRepository->getOrders($model);
    }

    /**
     * fill order items
     * @param $model
     */
    public function getOrdersItems($model)
    {
        $orders = $model->orders;

        foreach ($orders as $order)
        {
            $productIds = [];

            $orderItems = [];

            $newOrderItems = [];

            $orderProducts = $this->orderProductRepository->getOrderProducts($order->id);

            foreach ($orderProducts as $orderProduct)
            {
                $productIds[] = $orderProduct->product_id;
                $orderItems[] = [
                    'productId' => $orderProduct->product_id,
                    'sizeId' => $orderProduct->size_id,
                    'productCount' => $orderProduct->product_count,
                    'price' => $orderProduct->price
//                    'orderProductId' => $wishListProduct->id
                ];
            }

            $products = $this->productRepository->getOrdersProducts($productIds, $model->language, $model->user->user_type_id);

            foreach ($orderItems as $orderItem)
            {
                foreach ($products as $product)
                {
                    if ($orderItem['productId'] == $product->id)
                    {
                        $newOrderItems[] = [
//                            'wishListProductId' => $wishListItem['wishListProductId'],
                            'productId' => $orderItem['productId'],
                            'sizeId' => $orderItem['sizeId'],
                            'productCount' => $orderItem['productCount'],
                            'price' => $orderItem['price'],
                            'product' => $product
                        ];
                        $orderItem['product'] = $product;
                    }
                }
            }

            $order->orderItems = $newOrderItems;
        }
    }

    /**
     * fill orders total count
     * @param $model
     */
    public function getTotalOrdersCount($model)
    {
        $model->totalOrdersCount = $this->orderRepository->getTotalOrdersCount($model);
    }

    private function fillMetaTags($model)
    {
        $metaTag = $this->metaTagRepository->getMetaTagByPageName($model);
        $model->title = $metaTag->title;
        $model->description = $metaTag->description;
        $model->keywords = $metaTag->keywords;
        $model->h1 = $metaTag->h1;
    }
}