<?php
/**
 * Created by PhpStorm.
 * User: vlad_
 * Date: 27.11.2017
 * Time: 17:00
 */

namespace App\Services;

use App\Repositories\CategoryRepository;
use App\Repositories\ProductRepository;

/**
 * Class SearchService
 * @package App\Services
 */
class SearchService extends LayoutService
{
    /**
     * @var ProductRepository
     */
    private $productRepository;

    /**
     * SearchService constructor.
     * @param CategoryRepository $categoryRepository
     * @param ProductRepository $productRepository
     */
    public function __construct(CategoryRepository $categoryRepository, ProductRepository $productRepository)
    {
        parent::__construct($categoryRepository);

        $this->productRepository = $productRepository;
    }

    /**
     * @param $model
     */
    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub

        $this->fillSearchProducts($model);

        $this->fillCountSearchProducts($model);
    }

    /**
     * fill search products
     * @param $model
     */
    private function fillSearchProducts($model)
    {
        $model->searchProducts = $this->productRepository->getAllProductsForSearch($model);

        if (!$model->searchProducts->count())
        {
            abort(404);
        }
    }

    /**
     * fill count search products
     * @param $model
     */
    private function fillCountSearchProducts($model)
    {
        $model->countSearchProducts = $this->productRepository->getCountSearchProducts($model);
    }

    /**
     * fill model via ajax
     * @param $model
     */
    public function fillAjax($model)
    {
        $this->fillAjaxSearchProducts($model);
        $this->fillCountSearchProducts($model);
    }

    /**
     * fill ajax search products
     * @param $model
     */
    public function fillAjaxSearchProducts($model)
    {
        $model->searchProducts = $this->productRepository->getAjaxSearchProducts($model);
    }
}