<?php
/**
 * Created by PhpStorm.
 * User: vlad_
 * Date: 27.11.2017
 * Time: 17:00
 */

namespace App\Services;


use App\Repositories\CategoryRepository;
use App\Repositories\ProductRepository;

class SearchService extends LayoutService
{
    private $productRepository;

    public function __construct(CategoryRepository $categoryRepository, ProductRepository $productRepository)
    {
        parent::__construct($categoryRepository);

        $this->productRepository = $productRepository;
    }
    
    public function fill($model)
    {
        parent::fill($model); // TODO: Change the autogenerated stub

        $this->fillSearchProducts($model);

        $this->fillCountSearchProducts($model);
    }

    private function fillSearchProducts($model)
    {
        $model->searchProducts = $this->productRepository->getAllProductsForSearch($model);

        if (!$model->searchProducts->count())
        {
            abort(404);
        }
    }

    private function fillCountSearchProducts($model)
    {
        $model->countSearchProducts = $this->productRepository->getCountSearchProducts($model);
    }
    
    public function fillAjax($model)
    {
        $this->fillAjaxSearchProducts($model);
        $this->fillCountSearchProducts($model);
    }
    
    public function fillAjaxSearchProducts($model)
    {
        $model->searchProducts = $this->productRepository->getAjaxSearchProducts($model);
    }
}